using Microsoft.EntityFrameworkCore.Migrations;

namespace MicroK8s.Api.Migrations
{
    public partial class InitialSeeding : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 1, "Africa", "002" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 2, "Eastern Africa", "014" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 3, "Middle Africa", "017" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 4, "Northern Africa", "015" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 5, "Southern Africa", "018" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 6, "Western Africa", "011" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 7, "Americas", "019" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 8, "Latin America and the Caribbean", "419" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 9, "Caribbean", "029" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 10, "Central America", "013" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 11, "South America", "005" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 12, "Northern America", "021" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 13, "Asia", "142" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 14, "Central Asia", "143" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 15, "Eastern Asia", "030" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 16, "Southern Asia", "034" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 17, "South-Eastern Asia", "035" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 18, "Western Asia", "145" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 19, "Europe", "150" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 20, "Eastern Europe", "151" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 21, "Northern Europe", "154" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 22, "Southern Europe", "039" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 23, "Western Europe", "155" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 24, "Oceania", "009" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 25, "Australia and New Zealand", "053" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 26, "Melanesia", "054" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 27, "Micronesia", "057" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 28, "Polynesia", "061" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 29, "Asia Pacific", "ASP" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 30, "Americas", "AME" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 31, "Europe", "EUR" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 32, "Middle East and Africa", "MEA" }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Regions", columns: new[] { "Id", "Name", "Code" }, values: new object[] { 33, "Global", "GBL" }, schema: "Mdm");

            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 2, "United Arab Emirates", "AE", 18 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 3, "Afghanistan", "AF", 16 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 4, "Antigua And Barbuda", "AG", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 5, "Anguilla", "AI", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 6, "Albania", "AL", 22 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 7, "Armenia", "AM", 18 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 8, "Angola", "AO", 3 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 9, "Antarctica", "AQ", 12 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 10, "Argentina", "AR", 11 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 11, "American Samoa", "AS", 28 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 12, "Austria", "AT", 23 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 13, "Australia", "AU", 25 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 14, "Aruba", "AW", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 15, "Åland Islands", "AX", 21 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 16, "Azerbaijan", "AZ", 18 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 17, "Bosnia And Herzegovina", "BA", 22 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 18, "Barbados", "BB", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 19, "Bangladesh", "BD", 16 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 20, "Belgium", "BE", 23 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 21, "Burkina Faso", "BF", 6 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 22, "Bulgaria", "BG", 20 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 23, "Bahrain", "BH", 18 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 24, "Burundi", "BI", 2 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 25, "Benin", "BJ", 6 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 26, "Saint Barthélemy", "BL", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 27, "Bermuda", "BM", 12 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 28, "Brunei Darussalam", "BN", 17 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 29, "Bolivia, Plurinational State Of", "BO", 11 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 30, "Bonaire, Sint Eustatius And Saba", "BQ", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 31, "Brazil", "BR", 11 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 32, "Bahamas", "BS", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 33, "Bhutan", "BT", 16 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 34, "Bouvet Island", "BV", 11 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 35, "Botswana", "BW", 5 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 36, "Belarus", "BY", 20 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 37, "Belize", "BZ", 10 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 38, "Canada", "CA", 12 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 39, "Cocos (Keeling) Islands", "CC", 25 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 40, "Congo, The Democratic Republic Of The", "CD", 3 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 41, "Central African Republic", "CF", 3 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 42, "Congo", "CG", 3 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 43, "Switzerland", "CH", 23 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 44, "Côte D'Ivoire", "CI", 6 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 45, "Cook Islands", "CK", 28 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 46, "Chile", "CL", 11 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 47, "Cameroon", "CM", 3 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 48, "China", "CN", 15 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 49, "Colombia", "CO", 11 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 50, "Costa Rica", "CR", 10 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 51, "Cuba", "CU", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 52, "Cape Verde", "CV", 6 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 53, "Curaçao", "CW", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 54, "Christmas Island", "CX", 25 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 55, "Cyprus", "CY", 18 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 56, "Czech Republic", "CZ", 20 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 57, "Germany", "DE", 23 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 58, "Djibouti", "DJ", 2 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 59, "Denmark", "DK", 21 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 60, "Dominica", "DM", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 61, "Dominican Republic", "DO", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 62, "Algeria", "DZ", 4 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 63, "Ecuador", "EC", 11 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 64, "Estonia", "EE", 21 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 65, "Egypt", "EG", 4 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 66, "Western Sahara", "EH", 4 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 67, "Eritrea", "ER", 2 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 68, "Spain", "ES", 22 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 69, "Ethiopia", "ET", 2 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 70, "Finland", "FI", 21 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 71, "Fiji", "FJ", 26 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 72, "Falkland Islands (Malvinas)", "FK", 11 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 73, "Micronesia, Federated States Of", "FM", 27 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 74, "Faroe Islands", "FO", 21 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 75, "France", "FR", 23 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 76, "Gabon", "GA", 3 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 77, "United Kingdom", "GB", 21 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 78, "Grenada", "GD", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 79, "Georgia", "GE", 18 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 80, "French Guiana", "GF", 11 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 81, "Guernsey", "GG", 21 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 82, "Ghana", "GH", 6 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 83, "Gibraltar", "GI", 22 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 84, "Greenland", "GL", 12 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 85, "Gambia", "GM", 6 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 86, "Guinea", "GN", 6 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 87, "Guadeloupe", "GP", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 88, "Equatorial Guinea", "GQ", 3 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 89, "Greece", "GR", 22 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 90, "South Georgia And The South Sandwich Islands", "GS", 5 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 91, "Guatemala", "GT", 10 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 92, "Guam", "GU", 27 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 93, "Guinea-Bissau", "GW", 6 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 94, "Guyana", "GY", 11 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 95, "Hong Kong SAR, China", "HK", 15 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 96, "Heard Island And Mcdonald Islands", "HM", 21 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 97, "Honduras", "HN", 10 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 98, "Croatia", "HR", 22 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 99, "Haiti", "HT", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 100, "Hungary", "HU", 20 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 101, "Indonesia", "ID", 17 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 102, "Ireland", "IE", 21 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 103, "Israel", "IL", 18 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 104, "Isle Of Man", "IM", 21 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 105, "India", "IN", 16 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 107, "Iraq", "IQ", 18 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 108, "Iran, Islamic Republic Of", "IR", 16 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 109, "Iceland", "IS", 21 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 110, "Italy", "IT", 22 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 111, "Jersey", "JE", 21 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 112, "Jamaica", "JM", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 113, "Jordan", "JO", 18 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 114, "Japan", "JP", 15 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 115, "Kenya", "KE", 2 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 116, "Kyrgyzstan", "KG", 14 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 117, "Cambodia", "KH", 17 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 118, "Kiribati", "KI", 27 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 119, "Comoros", "KM", 2 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 120, "Saint Kitts And Nevis", "KN", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 121, "Korea, Democratic People'S Republic Of", "KP", 15 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 122, "Korea, Republic Of", "KR", 15 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 123, "Kuwait", "KW", 18 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 124, "Cayman Islands", "KY", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 125, "Kazakhstan", "KZ", 14 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 126, "Lao People'S Democratic Republic", "LA", 17 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 127, "Lebanon", "LB", 18 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 128, "Saint Lucia", "LC", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 129, "Liechtenstein", "LI", 23 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 130, "Sri Lanka", "LK", 16 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 131, "Liberia", "LR", 6 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 132, "Lesotho", "LS", 5 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 133, "Lithuania", "LT", 21 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 134, "Luxembourg", "LU", 23 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 135, "Latvia", "LV", 21 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 136, "Libya", "LY", 4 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 137, "Morocco", "MA", 4 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 138, "Monaco", "MC", 23 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 139, "Moldova, Republic Of", "MD", 20 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 140, "Montenegro", "ME", 22 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 141, "Saint Martin (French Part)", "MF", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 142, "Madagascar", "MG", 2 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 143, "Marshall Islands", "MH", 27 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 144, "Macedonia, The Former Yugoslav Republic Of", "MK", 22 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 145, "Mali", "ML", 6 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 146, "Myanmar", "MM", 17 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 147, "Mongolia", "MN", 15 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 148, "Macao SAR, China", "MO", 15 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 149, "Northern Mariana Islands", "MP", 27 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 150, "Martinique", "MQ", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 151, "Mauritania", "MR", 6 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 152, "Montserrat", "MS", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 153, "Malta", "MT", 22 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 154, "Mauritius", "MU", 2 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 155, "Maldives", "MV", 16 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 156, "Malawi", "MW", 2 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 157, "Mexico", "MX", 10 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 158, "Malaysia", "MY", 17 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 159, "Mozambique", "MZ", 2 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 160, "Namibia", "NA", 5 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 161, "New Caledonia", "NC", 26 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 162, "Niger", "NE", 6 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 163, "Norfolk Island", "NF", 25 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 164, "Nigeria", "NG", 6 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 165, "Nicaragua", "NI", 10 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 166, "Netherlands", "NL", 23 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 167, "Norway", "NO", 21 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 168, "Nepal", "NP", 16 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 169, "Nauru", "NR", 27 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 170, "Niue", "NU", 28 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 171, "New Zealand", "NZ", 25 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 172, "Oman", "OM", 18 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 173, "Panama", "PA", 10 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 174, "Peru", "PE", 11 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 175, "French Polynesia", "PF", 28 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 176, "Papua New Guinea", "PG", 26 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 177, "Philippines", "PH", 17 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 178, "Pakistan", "PK", 16 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 179, "Poland", "PL", 20 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 180, "Saint Pierre And Miquelon", "PM", 12 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 181, "Pitcairn", "PN", 28 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 182, "Puerto Rico", "PR", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 183, "Palestine, State Of", "PS", 18 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 184, "Portugal", "PT", 22 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 185, "Palau", "PW", 27 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 186, "Paraguay", "PY", 11 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 187, "Qatar", "QA", 18 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 188, "Réunion", "RE", 2 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 189, "Romania", "RO", 20 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 190, "Serbia", "RS", 22 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 191, "Russian Federation", "RU", 20 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 192, "Rwanda", "RW", 2 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 193, "Saudi Arabia", "SA", 18 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 194, "Solomon Islands", "SB", 26 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 195, "Seychelles", "SC", 2 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 196, "Sudan", "SD", 4 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 197, "Sweden", "SE", 21 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 198, "Singapore", "SG", 17 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 199, "Saint Helena, Ascension And Tristan Da Cunha", "SH", 6 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 200, "Slovenia", "SI", 22 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 201, "Svalbard And Jan Mayen", "SJ", 21 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 202, "Slovakia", "SK", 20 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 203, "Sierra Leone", "SL", 6 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 204, "San Marino", "SM", 22 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 205, "Senegal", "SN", 6 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 206, "Somalia", "SO", 2 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 207, "Suriname", "SR", 11 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 208, "Sao Tome And Principe", "ST", 3 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 209, "El Salvador", "SV", 10 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 210, "Sint Maarten (Dutch Part)", "SX", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 211, "Syrian Arab Republic", "SY", 18 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 212, "Swaziland", "SZ", 5 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 213, "Turks And Caicos Islands", "TC", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 214, "Chad", "TD", 3 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 215, "French Southern Territories", "TF", 11 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 216, "Togo", "TG", 6 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 217, "Thailand", "TH", 17 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 218, "Tajikistan", "TJ", 14 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 219, "Tokelau", "TK", 28 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 220, "Timor-Leste", "TL", 17 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 221, "Turkmenistan", "TM", 14 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 222, "Tunisia", "TN", 4 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 223, "Tonga", "TO", 28 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 224, "Turkey", "TR", 18 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 225, "Trinidad And Tobago", "TT", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 226, "Tuvalu", "TV", 28 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 227, "Taiwan, ROC", "TW", 15 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 228, "Tanzania, United Republic Of", "TZ", 2 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 229, "Ukraine", "UA", 20 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 230, "Uganda", "UG", 2 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 231, "United States Minor Outlying Islands", "UM", 12 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 232, "United States", "US", 12 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 233, "Uruguay", "UY", 11 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 234, "Uzbekistan", "UZ", 14 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 235, "Holy See (Vatican City State)", "VA", 22 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 236, "Saint Vincent And The Grenadines", "VC", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 237, "Venezuela, Bolivarian Republic Of", "VE", 11 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 238, "Virgin Islands, British", "VG", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 239, "Virgin Islands, U.S.", "VI", 9 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 240, "Vietnam", "VN", 17 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 241, "Vanuatu", "VU", 26 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 242, "Wallis And Futuna", "WF", 28 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 243, "Samoa", "WS", 28 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 245, "Yemen", "YE", 18 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 246, "Mayotte", "YT", 2 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 247, "South Africa", "ZA", 5 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 248, "Zambia", "ZM", 2 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 249, "Zimbabwe", "ZW", 2 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 254, "South Sudan", "SS", 2 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 256, "British Indian Ocean Territory", "IO", 17 }, schema: "Mdm");
            migrationBuilder.InsertData(table: "Countries", columns: new[] { "Id", "Name", "Code", "RegionId" }, values: new object[] { 257, "Andorra", "AD", 22 }, schema: "Mdm");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
