apiVersion: v1
kind: Service
metadata:
  name: microk8srazor-service
  namespace: bdn-poc
spec:
  type: NodePort
  selector:
    mylabel: microk8razor
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microk8srazor-api
  namespace: bdn-poc
spec:
  replicas: 2
  selector:
    matchLabels:
      mylabel: microk8razor
  template:
    metadata:
      labels:
        mylabel: microk8razor
    spec:
      containers:
        - name: microk8srazor-site
          image: ngarje/microk8srazor
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
          - name: "Redis__InstanceName"
            value: "bdn-poc-api"
          - name: "Redis__ConnectionString"
            value: "10.152.183.77:6379"
          - name: "ConnectionStrings__EfContext"
            value: "Data Source=10.138.108.40,31433;User ID=sa;Password=Testingmicrok8s;Database=MicroK8sApi"
          - name: "RabbitMq__Hostname"
            value: "10.152.183.209"
          - name: "RabbitMq__Port"
            value: "5672"
          - name: "RabbitMq__Password"
            value: "admin"
          - name: "RabbitMq__UserName"
            value: "admin"


