apiVersion: v1
kind: Service
metadata:
  labels:
    svc: microk8-ang-ui-svc
  name: microk8-ang-ui-svc-nlb
  namespace: bdn-poc
spec:
  type: NodePort
  ports:
  - name: microk8-ang-ui-svc-port
    port: 80
    nodePort: 30200

  selector:
    app: microk8ui #for creating a deployment in kubernetes
---
apiVersion: v1
kind: Service
metadata:
  labels:
    svc: microk8-ang-ui-svc
  name: microk8-ang-ui-svc
  namespace: bdn-poc
spec:
  type: ClusterIP
  ports:
  - name: microk8-ang-ui-svc-port
    port: 80
    protocol: TCP
  selector:
    app: microk8ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microk8-ang-ui-dep
  namespace: bdn-poc
spec:
  replicas: 2
  selector:
    matchLabels:
      app : microk8ui
  template:
    metadata:
      labels:
        app : microk8ui  
    spec:
      containers:
        - name: microk8-ang-ui-dep-cnt
          image: ngarje/microk8ui:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
            - name: BACKEND_API_URL
              value: "http://10.138.108.40"

