apiVersion: v1
kind: Service
metadata:
  labels:
    svc: microk8-api-svc
  name: microk8-api-svc
  namespace: bdn-poc
spec:
  type: ClusterIP
  ports:
  - name: microk8-api-svc-port
    port: 80
    protocol: TCP
  selector:
    app: microk8sapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microk8-api-dep
  namespace: bdn-poc
spec:
  replicas: 2
  selector:
    matchLabels:
      app : microk8sapi
  template:
    metadata:
      labels:
        app : microk8sapi  
    spec:
      containers:
        - name: microk8-api-dep-cnt
          image: ngarje/microk8sapi:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
          - name: "Redis__InstanceName"
            value: "bdn-poc-api"
          - name: "Redis__ConnectionString"
            value: "10.152.183.77:6379"
          - name: "ConnectionStrings__EfContext"
            value: "Data Source=10.138.108.40,31433;User ID=sa;Password=Testingmicrok8s;Database=MicroK8sApi"
          - name: "RabbitMq__Hostname"
            value: "10.152.183.209"
          - name: "RabbitMq__Port"
            value: "5672"
          - name: "RabbitMq__Password"
            value: "admin"
          - name: "RabbitMq__UserName"
            value: "admin"